Rename shapely.apply to shapely.transform
shapely/shapely pull request #1393
Opened 2022-05-22 08:48 UTC by jorisvandenbossche

xref https://github.com/shapely/shapely/issues/1276 about naming inconsistencies

Shapely uses "transform" for what is called `apply` for the vectorized functions (merged from pygeos). This PR renames `apply()` to `transform()`.

I personally think both names are fine, so this change keeps it a bit more consistent in shapely. 

(I might actually even like "transform" a bit more, as it signals more that the geometry coordinates are only transformed, keeping the exact structure. While applying a function in general could return something else as geometries. For example, in pandas, there is a more generic "apply" (that can basically return anything) vs more specific "transform" (which is guaranteed to keep the same shaped output))

2022-05-22 23:18 UTC, mwtoews approved these changes
Yes to "transform" for this type of operation.

A new GEOS 3.11 feature is [`GEOSGeom_transformXY`](https://github.com/libgeos/geos/blob/2a82afc1ac2327966f56bdf35a6d88aaadb81330/capi/geos_c.h.in#L3846-L3861) (and [`GEOSTransformXYCallback`](https://github.com/libgeos/geos/blob/2a82afc1ac2327966f56bdf35a6d88aaadb81330/capi/geos_c.h.in#L278-L293)). This functionality has not yet made it into Shapely yet, although I can see that it would be useful optimization for "(N, 2)->(N, 2)" cases within `shapely.coordinates.transform()`.

2022-05-23 16:09 UTC, brendan-ward approved these changes
+1 on the name change

2022-06-06 19:02 UTC, sgillies approved these changes

2022-06-06 19:04 UTC, caspervdw requested changes

2022-06-06 19:04 UTC, caspervdw commented on shapely/coordinates.py
> +def transform(geometry, transformation, include_z=False):
The docstring should also be adjusted

2022-06-13 13:22 UTC, jorisvandenbossche commented
> And maybe also change the names all the way down to C?

The method currently only lives on the python side (the actual C funcs being called here are `get_coordinates` and `set_coordinates`, `apply`/`transform` being a python wrapper around those with calling the transform func in the middle)

2022-06-13 13:23 UTC, jorisvandenbossche commented on shapely/coordinates.py
> +def transform(geometry, transformation, include_z=False):
Updated the docstring

2022-06-19 14:53 UTC, merged