Update segmentize tolerance parameter to max segment length
shapely/shapely pull request #1506
Opened 2022-08-27 09:55 UTC by akadouri

- Renamed parameter
- Updated function description
- Updated tests

2022-08-28 15:28 UTC, jorisvandenbossche reviewed
Looking good, thanks!

One more thing: there is also a `segmentize` method in shapely/geometry/base.py, that needs to be updated as well

2022-08-28 20:56 UTC, akadouri commented
Did not realize re-requesting a review would remove the other reviewer 🤷

@jorisvandenbossche Is there somewhere I should note this change? It will break older implementations that use `segmentize` with `tolerance=` (at least those using [2.0a1](https://github.com/shapely/shapely/releases/tag/2.0a1))

2022-08-29 18:18 UTC, brendan-ward requested changes
@akadouri thanks for working on this!  

Since this is targeting a major version release and only showed up briefly in shapely, I think we can skip a deprecation period here.

Agreed on need to document this as a breaking change for both shapely 2.0a1 and also for pygeos under #1500; I don't think we have a place yet for either.  @jorisvandenbossche can advise, but I think so long as we make sure to document this change, this PR can get merged once the typos are fixed.

2022-08-29 18:18 UTC, brendan-ward commented on shapely/constructive.py
> +    so that segments are longer than the provided maximum segment length.  New vertices
```suggestion
    so that segments are no longer than the provided maximum segment length.  New vertices
```

2022-08-29 18:18 UTC, brendan-ward commented on shapely/geometry/base.py
> +        so that segments are longer than the provided maximum segment length.  New
```suggestion
        so that segments are no longer than the provided maximum segment length.  New
```

2022-08-29 20:20 UTC, jorisvandenbossche commented
> Since this is targeting a major version release and only showed up briefly in shapely, I think we can skip a deprecation period here.

To be clear, the PR isn't adding deprecations and just changing, so I assume you are agreeing ;)

> Agreed on need to document this as a breaking change for both shapely 2.0a1 and also for pygeos under #1500; I don't think we have a place yet for either. @jorisvandenbossche can advise, but I think so long as we make sure to document this change, this PR can get merged once the typos are fixed.

Yeah, for pygeos it can go in the to-be-written migration guide for pygeos. For shapely 2.0a1 -> 2.0b1, we don't have a place. And I don't want to include it in the main changelog for 2.0 (as it is just a distraction later on for people reading the 2.0.0 release notes). Maybe we can include those actual releases (a1, b1, etc) in CHANGES.txt and so mention it there? (although that might also get a bit messy later on to know what needs to be documented where)

(to be honest, I also don't think this particular case is very important. Exactly because it is a new function, I don't think that many people will already started using it in shapely 2.0a1, unless they were migrating from pygeos, for which we certainly need a guide as well)

2022-08-30 17:32 UTC, akadouri commented
Thanks for the feedback. Yeah that makes sense with how few are likely already relying on it in shapely 2.0a1.

2022-09-05 18:30 UTC, jorisvandenbossche commented
@brendan-ward I added a small note for this change in CHANGES.txt. Together with the changes in https://github.com/shapely/shapely/pull/1520, I think we can keep such a note in CHANGES.txt, while the release docs just focus on the full 2.0.0 release. 

For pygeos, we can include this later when tackling https://github.com/shapely/shapely/issues/1500

2022-09-09 07:18 UTC, merged

2022-09-09 07:18 UTC, jorisvandenbossche commented
Thanks @akadouri !